--- 
- hosts: all
  become: yes

  tasks:
    - import_tasks: tasks/all/essential.yml

# - hosts: local
#   become: yes

#   tasks: 
#     - import_tasks: tasks/local/services.yml

- hosts: aws
  become: yes

  tasks: 
    - import_tasks: tasks/aws/services.yml