version: '2'

services:
  nextcloud-db:
    container_name: nextcloud-db 
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  nextcloud-server:
    container_name: nextcloud-server
    image: nextcloud
    restart: always
    ports:
      - 80:80
    links:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - nextcloud-server/:/var/www/html
      - nextcloud-data/:/var/www/html/data
    environment:
      - REDIS_HOST=nextcloud-redis
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=nextcloud-db

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis
    restart: always

  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nextcloud-server:
  nextcloud-db:
  nextcloud-redis: