version: '2'

services:
  nextcloud-server:
    container_name: nextcloud-server
    image: nextcloud
    restart: always
    ports:
      - 80:80
    links:
      - nextcloud-redis
    volumes:
      - /containers/nextcloud-server/:/var/www/html
      - /objects/nextcloud-data/:/var/www/html/data
    environment:
      - REDIS_HOST=nextcloud-redis
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis
    restart: always

  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nextcloud-server:
  nextcloud-redis: