version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
     - ./nginx:/etc/nginx
     - ./www:/var/www/html
    links:
      - db
      - php

  db:
    container_name: db 
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=photographic
      - MYSQL_USER=db-user
      
  php:
    container_name: php
    image: php:fpm-alpine3.19
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/html
    # command: docker-php-ext-install mysqli

volumes:
  php: