- name: Update Packages 
  apt:
    update_cache: yes
    name: "*"
    state: latest

- name: Install essential packages
  apt:
    pkg:
    - screen
    - htop
    - vim
    - unattended-upgrades
    - apt-listchanges
    state: latest
  become: yes

- name: Create User - "{{ username }}"
  user:
    name: "{{ username }}"
    state: "present"
    system: true
    shell: /bin/bash

- name: Ensure the user is accessible
  authorized_key:
    user: "{{ username }}"
    state: "present"
    key: "{{ lookup('file', 'keys/ansible_key.pub') }}"

- name: Disable SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  become: yes
  register: sshd_config

- name: Enable passwordless sudo for "{{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  become: yes

- name: Restart SSH on config change
  service:
    name: ssh
    state: restarted
  become: yes
  when: sshd_config.changed

- name: Create unattended-upgrades apt configuration stub
  command:
    cmd: echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections

- name: Reconfigure apt to use unattended-upgrades
  command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades

- name: Start and enable unattended-upgrades service
  service: 
    name: unattended-upgrades
    enabled: yes
    state: started